 <div class="section">
      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 s12">
          <div class="icon-block">
            <h2 class="center light-red-text"><i class="material-icons">flash_on</i></h2>
            <h5 class="center">UFO</h5>

            <p class="light">It means we cannot find what you are looking for here on Earth. Is this something from outer space?</p>
          </div>
        </div>
      </div>

</div>