<div class="container medium-top-padding">
    <h5 class="orange-text darken-4">Snippet <?= $snippet->title; ?></h5>
    <div class="snippet-info"><?= $this->dateSvc->humanFriendly($snippet->updated_at, 'Y-m-d H:i:s'); ?>
        <?php if (isset($snippet->creator->detail)) : ?>
            by <?= $snippet->creator->detail->firstname; ?> <?= $snippet->creator->detail->lastname; ?>
        <?php elseif(isset($snippet->creator->username)) : ?>
            by <?= $snippet->creator->username; ?>
        <?php endif; ?>
        <div class="categories">
        <?php foreach ($snippet->categories as $category ):?>
            <a href="<?= $this->url->get([
                'for' => 'snippet-list-by-category',
                'categoryName' => $category->name
            ]); ?>"><div class="chip"><?= $category->name; ?></div></a>
        <?php endforeach;?>
        </div>
    </div>
    <pre>
        <code><?= $snippet->content; ?></code>
    </pre>
</div>
