  <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <h1 class="header center orange-text">Snipp it now</h1>
      <div class="row center">
        <h5 class="header col s12 light">Code-sharing made easy</h5>
      </div>
      <div class="row center">
        <form id="createsnippet" class="col s12" action="<?= $this->url->get('/create'); ?>" method="post">
          <input id="csrfToken" type="hidden" name="<?= $token->name; ?>" value="<?= $token->value; ?>">

          <div class="row">
            <div class="input-field col s12">
              <textarea id="snippet" name="snippet" class="materialize-textarea"></textarea>
              <label for="snippet">Paste here</label>
            </div>
          </div>

          <div class="row">
            <div class="progress">
                <div class="indeterminate"></div>
            </div>
          </div>
          <div class="row center">
            <button type="submit" class="btn-large waves-effect waves-light orange">Create Snippet</button>
          </div>
        </form>
      </div>
    </div>
  </div>

<?php if(isset($featuredSnippets)) : ?>
  <ul class="collection">
      <?php foreach($featuredSnippets as $snippet) : ?>
          <li class="collection-item avatar">
            <i class="material-icons circle red">play_arrow</i>
            <span class="title"><?= $snippet->title; ?></span>
            <p><?= $snippet->updated_at; ?></p>
            <a href="<?= $appUrl; ?>s/<?= $snippet->id; ?>" class="secondary-content"><i class="material-icons">grade</i></a>
          </li>
      <?php endforeach; ?>
  </ul>
<?php endif; ?>