  <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <h1 class="header center orange-text">Snipp it now</h1>
      <div class="row center">
        <h5 class="header col s12 light">Code-sharing made easy</h5>
      </div>
      <div class="row center">
        <form class="col s12" action="<?= $this->url->get('snippet/create'); ?>" method="post">
          <div class="row">
            <div class="input-field col s12">
              <textarea id="snippet" class="materialize-textarea"></textarea>
              <label for="snippet">Paste here</label>
            </div>
          </div>
          <div class="row center">
            <button type="submit" class="btn-large waves-effect waves-light orange">Create Snippet</button>
          </div>
        </form>
      </div>

    </div>
  </div>


    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m6">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2>
            <h5 class="center">Paste it</h5>

            <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
          </div>
        </div>

        <div class="col s12 m6">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">group</i></h2>
            <h5 class="center">Share it</h5>

            <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
          </div>
        </div>

      </div>

    </div>
