  <footer class="page-footer green">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">About</h5>
          <p class="grey-text text-lighten-4">Snipp.id is fast and simple snippet-sharing service.</p>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Copyright 2017 <a class="green-text text-lighten-3" href="http://juhara.com">juhara.com</a>
      </div>
    </div>
  </footer>
