<div class="fixed-action-btn">
    <a class="btn-floating btn-large waves-effect waves-light blue" href="<?= $this->url->get('/'); ?>"><i class="material-icons">add</i></a>
</div>
<footer class="page-footer orange darken-2">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <p class="grey-text text-lighten-4">Snipp.id is fast and simple snippet-sharing service.</p>
        </div>
      </div>
    </div>
    <div class="footer-copyright orange darken-3">
      <div class="container">
      Copyright 2017 <a class="white-text text-lighten-3" href="http://juhara.com">juhara.com</a>
      </div>
    </div>
</footer>
