  <nav class=" green lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="<?= $this->url->get('/'); ?>" class="brand-logo"><?= $appName; ?></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="<?= $this->url->get('/'); ?>"><i class="material-icons left">home</i>Home</a></li>
        <li><a href="<?= $this->url->get('/search'); ?>"><i class="material-icons left">search</i>Search</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="<?= $this->url->get('/'); ?>"><i class="material-icons left">home</i>Home</a></li>
        <li><a href="<?= $this->url->get('/search'); ?>"><i class="material-icons left">search</i>Search</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <br><br>
      <h1 class="header center orange-text">Starter Template</h1>
      <div class="row center">
        <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
      </div>
      <div class="row center">
        <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light orange">Get Started</a>
      </div>
      <br><br>

    </div>
  </div>
