  <nav class="orange lighten-1" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="<?= $this->url->get('/'); ?>" class="brand-logo"><?= $appName; ?></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="<?= $this->url->get('/'); ?>"><i class="material-icons left">home</i>Home</a></li>
        <li><a href="<?= $this->url->get('list'); ?>"><i class="material-icons left">list</i>Snippets</a></li>

        <?php if (isset($user)) : ?>
        <li><a class="userprofile" data-activates="dropdownprofile" href="#!"><i class="material-icons left">account_circle</i><?= $user->username; ?><i class="material-icons right">arrow_drop_down</i></a>
            <ul id="dropdownprofile" class="dropdown-content">
                <li><a class=" orange-text" href="<?= $this->url->get('signout'); ?>"><i class="material-icons left">perm_identity</i>Profile</a></li>
                <li><a class=" orange-text" href="<?= $this->url->get('your-snippets'); ?>"><i class="material-icons left">view_list</i>Snippets</a></li>
                <li class="divider"></li>
                <li><a class=" orange-text" href="<?= $this->url->get('signout'); ?>"><i class="material-icons left">input</i>Sign Out</a></li>
            </ul>
        </li>
        <?php else : ?>
        <li><a href="<?= $this->url->get('signin'); ?>"><i class="material-icons left">account_circle</i>Sign In</a></li>
        <?php endif; ?>

      </ul>

      <ul id="nav-mobile" class="side-nav">
        <?php if (isset($user)) : ?>
            <li>
              <div class="userView">
                <div class="background">
                  <img src="http://img.juhara.com/300x300.png">
                </div>
                <a href="#!user"><img class="circle" src="http://img.juhara.com/100x100.png"></a>
                <?php if(isset($userdetail)) : ?>
                  <a href="#!name"><span class="white-text name"><?= $userdetail->firstname; ?> <?= $userdetail->lastname; ?></span></a>
                <?php else : ?>
                  <a href="#!name"><span class="white-text name"><?= $user->username; ?></span></a>
                <?php endif; ?>
                <a href="#!email"><span class="white-text email"><?= $user->email; ?></span></a>
              </div>
            </li>
        <?php endif; ?>
        <li><a class="waves-effect" href="<?= $this->url->get('/'); ?>"><i class="material-icons">home</i>Home</a></li>
        <li><a class="waves-effect" href="<?= $this->url->get('list'); ?>"><i class="material-icons">list</i>Snippets</a></li>

        <?php if (isset($user)) : ?>
            <li><div class="divider"></div></li>
            <!-- <li><a class="subheader">Subheader</a></li> -->
            <li><a class="waves-effect" href="<?= $this->url->get('signout'); ?>"><i class="material-icons left">input</i>Sign Out</a></li>
        <?php else: ?>
            <li><a class="waves-effect" href="<?= $this->url->get('signin'); ?>"><i class="material-icons left">account_circle</i>Sign In</a></li>
        <?php endif; ?>

      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
