<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title><?= (isset($pageTitle) ? $pageTitle . ' - ' . $appName : $appName); ?></title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="/assets/<?= $theme; ?>/css/materialize.min.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="/assets/<?= $theme; ?>/css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="/assets/<?= $theme; ?>/js/highlight/styles/default.css" rel="stylesheet" >
</head>
<body>
  <?= $this->partial('header'); ?>
  <?= $this->getContent(); ?>
  <?= $this->partial('footer'); ?>

  <!--  Scripts-->
  <script src="/assets/<?= $theme; ?>/js/jquery.min.js"></script>
  <script src="/assets/<?= $theme; ?>/js/materialize.min.js"></script>
  <script src="/assets/<?= $theme; ?>/js/init.js"></script>
  <?= isset($customJs) ? $customJs : ''; ?>
  </body>
</html>
