<?php
  $currentUrl = preg_replace('{/$}', '', $appUrl) . $this->router->getRewriteUri();
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title><?= (isset($pageTitle) ? $pageTitle . ' - ' . $appName : $appName); ?></title>
  <meta property="og:url" content="<?= $currentUrl; ?>" />
  <meta name="twitter:url" content="<?= $currentUrl; ?>" />

  <meta property="og:type" content="article" />
  <meta name="twitter:card" content="summary" />

  <meta property="og:title" content="<?= (isset($pageTitle) ? $pageTitle . ' - ' . $appName : $appName); ?>" />
  <meta name="twitter:title" content="<?= (isset($pageTitle) ? $pageTitle . ' - ' . $appName : $appName); ?>" />

  <?php if (isset($pageDescription)) : ?>
      <meta property="og:description" content="<?= $pageDescription; ?>" />
      <meta name="description" content="<?= $pageDescription; ?>"/>
      <meta name="twitter:description" content="<?= $pageDescription; ?>" />
  <?php else : ?>
      <meta property="og:description" content="<?= $appDefaultDescription; ?>" />
      <meta name="description" content="<?= $appDefaultDescription; ?>"/>
      <meta name="twitter:description" content="<?= $appDefaultDescription; ?>" />
  <?php endif; ?>

  <?php if (isset($pageKeywords)) : ?>
      <meta name="keywords" content="<?= $pageKeywords; ?>"/>
  <?php else : ?>
      <meta name="keywords" content="<?= $appDefaultKeywords; ?>"/>
  <?php endif; ?>

  <meta property="og:image" content="http://img.juhara.com/100x100.png" />
  <meta name="twitter:image" content="http://img.juhara.com/100x100.png" />

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="<?= $appUrl; ?>assets/<?= $theme; ?>/css/materialize.min.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="<?= $appUrl; ?>assets/<?= $theme; ?>/css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="<?= $appUrl; ?>assets/<?= $theme; ?>/js/highlight/styles/default.css" rel="stylesheet" >
</head>
<body>
  <?= $this->partial('header'); ?>
  <?= $this->getContent(); ?>
  <?= $this->partial('footer'); ?>

  <!--  Scripts-->
  <script src="<?= $appUrl; ?>assets/<?= $theme; ?>/js/jquery.min.js"></script>
  <script src="<?= $appUrl; ?>assets/<?= $theme; ?>/js/materialize.min.js"></script>
  <script src="<?= $appUrl; ?>assets/<?= $theme; ?>/js/init.js"></script>
  <?= isset($customJs) ? $customJs : ''; ?>
  </body>
</html>
