<ul class="collection">
    <?php foreach ($snippets as $snippet) : ?>
    <li class="collection-item avatar">
        <i class="material-icons circle orange">1</i>
        <a href="<?= $this->url->get([ 'for' => 'snippet-detail', 'snippetId' => $snippet->id ]); ?>"><h3 class="title"><?= $snippet->title; ?></h3></a>
        <div><?= $this->dateSvc->humanFriendly($snippet->updated_at, 'Y-m-d H:i:s'); ?></div>
        <?php if (isset($snippet->creator->username)) : ?>
            <a href="<?= $this->url->get([ 'for' => 'snippet-list-by-user', 'username' => $snippet->creator->username ]); ?>"><div class="chip"><img src="http://img.juhara.com/50x50.png" alt="Contact Person"><?= $snippet->creator->username; ?></div></a>
        <?php endif ?>
        <a class="secondary-content" href="<?= $this->url->get([ 'for' => 'snippet-detail', 'snippetId' => $snippet->id ]); ?>">View</a>
    </li>
    <?php endforeach; ?>
</ul>
