<h5 class="orange-text">Sign In</h5>
<div class="row">
    <form class="snippetapp col s12">
      <div class="row">
        <div class="input-field col s12">
          <input id="email" type="email" class="validate">
          <label for="email">Email</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="password" type="password" class="validate">
          <label for="password">Password</label>
        </div>
      </div>
      <div class="row">
          <button type="submit" class="btn-large waves-effect waves-light orange" >Sign In</button>
      </div>
    </form>

    <div>Don't have account? <a href="<?= $this->url->get('signup'); ?>" >Sign Up</a></div>
  </div>