<div class="container medium-top-padding">
<h5 class="orange-text">Sign In</h5>
<div class="row">
    <form class="snippetapp col s12" action="auth" method="post">
      <input id="csrfToken" type="hidden" name="<?= $token->name; ?>" value="<?= $token->value; ?>">
      <div class="row">
        <div class="input-field col s12">
          <input id="username" name="username" type="text" class="validate">
          <label for="username">Username or Email</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="password" name="password" type="password" class="validate">
          <label for="password">Password</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <button type="submit" class="btn-large waves-effect waves-light orange" >Sign In</button>
        </div>
      </div>
      <div class="row">
        <div class="col s12">
            <div>Don't have account? <a href="<?= $this->url->get('signup'); ?>" >Sign Up</a></div>
        </div>
      </div>
    </form>
  </div>
</div>