<div class="container  medium-top-padding">
    <h5 class="orange-text darken-4">Snippets in <?= $categoryName; ?></h5>
    <div class="row">
        <div class="col s12">
            <span class="new badge orange" data-badge-caption="snippets"><?= $totalSnippets; ?></span>
        </div>
    </div>
    <div class="row">
        <?php foreach ($snippets as $snippet) : ?>
        <div class="col s12 m4">
          <div class="card horizontal">
            <div class="card-image">
              <img src="http://img.juhara.com/80x150.png">
            </div>
            <div class="card-stacked">
              <div class="card-title"><?= $snippet->title; ?></div>
              <div class="card-content">
                <p><?= $snippet->updated_at; ?></p>
              </div>
              <div class="card-action">
                <a href="<?= $appUrl .'s/' . $snippet->id; ?>">View</a>
                <?php if (isset($snippet->creator->username)) : ?>
                <div class="chip"><img src="http://img.juhara.com/50x50.png" alt="Contact Person"><?= $snippet->creator->username; ?></div>
              <?php endif ?>
              </div>
            </div>
          </div>
        </div>
        <?php endforeach; ?>
    </div><!-- fux -->

    <?= $page->buildPagination(); ?>
</div><!-- die -->
