<div class="container  medium-top-padding">
    <h5 class="orange-text darken-4">Snippets in <?= $categoryName; ?></h5>
    <div class="row">
        <div class="col s12">
            <span class="new badge orange" data-badge-caption="snippets"><?= $totalSnippets; ?></span>
        </div>
    </div>
    <?= $this->view->getPartial('list', [ 'snippets' => $snippets ]); ?>
    <?= $page->buildPagination(); ?>
</div>
