<h5 class="orange-text darken-4">Snippet List</h5>
<div class="row">
<?php foreach ($featuredSnippets as $snippet) : ?>
  <div class="col s12 m4">
    <div class="card horizontal">
      <div class="card-image">
        <img src="http://img.juhara.com/80x150.png">
      </div>
      <div class="card-stacked">
        <div class="card-title"><?= $snippet->title; ?></div>
        <div class="card-content">
          <p><?= $snippet->updated_at; ?></p>
        </div>
        <div class="card-action">
          <a href="<?= $appUrl .'s/' . $snippet->id; ?>">View</a>
          <div class="chip"><img src="http://img.juhara.com/50x50.png" alt="Contact Person">Jane Doe</div>
        </div>
      </div>
    </div>
  </div>
<?php endforeach; ?>
</div>


   <ul class="pagination">
    <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
    <li class="active"><a href="#!">1</a></li>
    <li class="waves-effect"><a href="#!">2</a></li>
    <li class="waves-effect"><a href="#!">3</a></li>
    <li class="waves-effect"><a href="#!">4</a></li>
    <li class="waves-effect"><a href="#!">5</a></li>
    <li class="waves-effect"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
  </ul>