<div class="container">
 <div class="section">
      <!--   Icon Section   -->
      <div class="row center">
        <div class="col s12 s12">
          <div class="icon-block">
            <h2 class="center orange-text darken-4"><i class="material-icons">flash_on</i></h2>
            <h5 class="center orange-text darken-4">Oops you enter hangar 21</h5>
            <p class="light center">It means you try to enter a very top secret area on Earth and you don't bring your key.</p>
            <p class="light center"><a class="waves-effect waves-light btn orange" href="<?= $this->url->get('/'); ?>">Back to Home</a></p>
          </div>
        </div>
      </div>
</div>
</div>
